"""
Aevus Testbed — Alert Data Model
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel


class Alert(BaseModel):
    """An alert generated by the threshold engine."""

    id: str
    severity: Literal["critical", "warning", "info"]
    asset_id: str
    asset_name: str
    message: str
    risk_score: int | None = None  # 0-100
    detected_at: datetime
    acknowledged_at: datetime | None = None
    resolved_at: datetime | None = None
    status: Literal["open", "acknowledged", "resolved"] = "open"
