"""
Aevus Testbed — Alert Data Model
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, Literal


class Alert(BaseModel):
    """An alert generated by the threshold engine."""

    id: str
    severity: Literal["critical", "warning", "info"]
    asset_id: str
    asset_name: str
    message: str
    risk_score: Optional[int] = None  # 0-100
    detected_at: datetime
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    status: Literal["open", "acknowledged", "resolved"] = "open"
